version: '2'

services:
    dctest-base:
        image: dctest/base
        volumes:
            - .:/dctest

    dctest-build_tools_base:
        image: dctest/build_tools_base
        volumes:
            - .:/dctest
